spring.application.name=banco-bff

server.port=8080

cuentas-service.url=http://localhost:8081
solicitudes-service.url=http://localhost:8082

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_ZFkLXbwTI
