spring.application.name=solicitudes-service

spring.application.name=solicitudes-service

server.port=8082

spring.datasource.url=jdbc:mysql://bancocloud-db.cqskb4xmsx2d.us-east-1.rds.amazonaws.com:3306/bancocloud?useSSL=true&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=Duocuc.2025

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
